# Generated by Django 6.0.4 on 2026-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icz', models.CharField(db_index=True, help_text='Идентификационный код закупки', max_length=100, unique=True, verbose_name='ИКЗ')),
                ('object_name', models.CharField(db_index=True, max_length=500, verbose_name='Наименование объекта закупки')),
                ('customer_full_name', models.CharField(max_length=500, verbose_name='Заказчик')),
                ('region', models.CharField(db_index=True, max_length=200, verbose_name='Регион')),
                ('procurement_method', models.CharField(max_length=200, verbose_name='Способ определения поставщика')),
                ('stage', models.CharField(max_length=100, verbose_name='Этап закупки')),
                ('start_date_time', models.DateTimeField(verbose_name='Начало подачи заявок')),
                ('end_date_time', models.DateTimeField(verbose_name='Окончание подачи заявок')),
                ('results_date', models.DateField(verbose_name='Дата подведения итогов')),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='НМЦК, ₽')),
                ('contract_execution_period', models.CharField(max_length=100, verbose_name='Срок исполнения контракта')),
                ('participant_requirements', models.TextField(verbose_name='Требования к участникам')),
                ('advantages', models.TextField(blank=True, null=True, verbose_name='Преимущества (СМП, СОНО и т.д.)')),
                ('delivery_place', models.TextField(verbose_name='Место поставки/выполнения работ')),
                ('bid_security_required', models.BooleanField(default=False, verbose_name='Обеспечение заявки')),
                ('bid_security_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер обеспечения заявки')),
                ('performance_required', models.BooleanField(default=True, verbose_name='Обеспечение исполнения контракта')),
                ('performance_security_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер обеспечения исполнения')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail заказчика')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('electronic_platform_name', models.CharField(max_length=200, verbose_name='Электронная площадка')),
                ('electronic_platform_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на площадку')),
            ],
            options={
                'verbose_name': 'Закупка (44-ФЗ)',
                'verbose_name_plural': 'Закупки (44-ФЗ)',
                'ordering': ['-end_date_time'],
                'indexes': [models.Index(fields=['icz'], name='page_tender_icz_76e04f_idx'), models.Index(fields=['region'], name='page_tender_region_33f1bd_idx'), models.Index(fields=['end_date_time'], name='page_tender_end_dat_906387_idx')],
            },
        ),
    ]
